apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-broker1
  namespace: kafka-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker-1
  serviceName: kafka1
  template:
    metadata:
      labels:
        app: kafka-broker-1
    spec:
      containers:
      - env:
        - name: KAFKA_LISTENERS
          value: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: INTERNAL://kafka1:9092,EXTERNAL://172.16.0.58:19092
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: INTERNAL
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181 # ,zoo2:2181,zoo3:2181
        - name: KAFKA_LOG_DIRS
          value: /kafka/kafka-logs
        - name: KAFKA_JMX_PORT
          value: "5555"
        - name: TOPIC_TIMESTAMP_TYPE
          value: LogAppendTime
        - name: KAFKA_CREATE_TOPICS
          value: flink-input:10:1,flink-output:10:1:compact
        image: wurstmeister/kafka:2.11-2.0.1
        imagePullPolicy: IfNotPresent
        name: kafka-broker1
        ports:
        - containerPort: 9092
        - containerPort: 19092
        volumeMounts:
        - mountPath: /kafka/kafka-logs
          name: rwvolume
      volumes:
      - name: rwvolume
        volumeClaimTemplates:
        - metadata:
            name: rwvolume
          spec:
            accessModes:
            - ReadWriteOnce
            storageClassName: "standard"
            resources:
              requests:
                storage: 1Gi
