apiVersion: v1
kind: Service
metadata:
  name: kafka2
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
  namespace: kafka-cluster
  labels:
    app: kafka-broker-1
spec:
  ports:
  - port: 19092
    targetPort: 19092
    protocol: TCP
  selector:
    app: kafka-broker-1
  type: LoadBalancer
  externalTrafficPolicy: Cluster