apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-broker1
  namespace: kafka-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker-1
  serviceName: kafka1
  template:
    metadata:
      labels:
        app: kafka-broker-1
    spec:
      containers:
      - env:



        # - name: KAFKA_LISTENERS
        #   value: "INSIDE://:9092,OUTSIDE://:8080"
        # - name: KAFKA_ADVERTISED_LISTENERS
        #   value: "INSIDE://:9092,OUTSIDE://kafka1.kafka-cluster.svc.cluster.local:8080"
        # - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
        #   value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT" # not production-ready!
        # - name: KAFKA_INTER_BROKER_LISTENER_NAME
        #   value: INSIDE
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka1
        # - name: KAFKA_ADVERTISED_LISTENERS
        #   value: PLAINTEXT://kafka1:9092
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181 # ,zoo2:2181,zoo3:2181
        - name: KAFKA_LOG_DIRS
          value: /kafka/kafka-logs
        # - name: KAFKA_BROKER_ID
        #   value: "1"
        - name: KAFKA_JMX_PORT
          value: "5555"
        # - name: KAFKA_CLEANUP_POLICY
        #   value: compact
        - name: TOPIC_TIMESTAMP_TYPE
          value: LogAppendTime
        image: wurstmeister/kafka:2.11-2.0.1
        imagePullPolicy: IfNotPresent
        name: kafka-broker1
        ports:
        - containerPort: 9092
        volumeMounts:
        - mountPath: /kafka/kafka-logs
          name: rwvolume
      volumes:
      - name: rwvolume
        volumeClaimTemplates:
        - metadata:
            name: rwvolume
          spec:
            accessModes:
            - ReadWriteOnce
            storageClassName: "standard"
            resources:
              requests:
                storage: 1Gi
